name: Github Jira Sync
on:
  pull_request:
    types:
      [
        labeled,
        unlabeled,
        opened,
        closed,
        reopened,
        ready_for_review,
        review_requested,
        review_request_removed,
      ]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  gh-jira-job:
    runs-on: ubuntu-latest
    steps:
      - name: Gh-Jira sync action
        id: gh-jira
        uses: srikar-samudrala/gh-jira-sync@v0.0.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
